# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
