# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
