# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170718_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='general', editable=False),
            preserve_default=False,
        ),
    ]
