# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 17:08
from __future__ import unicode_literals

import blog.formatChecker
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True),
        ),
    ]
