# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image_url',
        ),
    ]
