# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170721_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
    ]
