# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 19:32
from __future__ import unicode_literals

import blog.formatChecker
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170725_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=blog.models.content_image_directory),
        ),
    ]
