# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170725_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
