# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170725_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
