# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170725_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
