# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_userprofile_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
