# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20170730_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptrack',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
