# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20170807_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
