# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20170819_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedewImportant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
