# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 18:14
from __future__ import unicode_literals

import blog.formatChecker
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_timedewimportant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='other_image',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=blog.models.content_image_directory),
        ),
    ]
