# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_contentimage_other_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='other_image_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
