# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 18:33
from __future__ import unicode_literals

import blog.formatChecker
import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_contentimage_other_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='third_image',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=blog.models.content_image_directory),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='third_image_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
